### ISSUE TITLE
Adapter API

### ISSUE THREAD

**Issue by gladish** [gladish/portabledsb#2]
So that we can develop adapters in parallel to the DSB, we need to nail down the API between the Adapter and the DSB.

We also want to make sure the appropriate pieces (headers, maybe .so) get's installed into a location where Adapters can pick it up.

**Comment by gladish** [comment]
I also think the Adapter API is supposed to be free of AllJoyn Core dependencies. i.e. Not requie headers from AllJoyn Core, just headers from DSB.

**Comment by xiaooquanwu** [comment]
what plan for support event/action and controlpanel ？
